# Generated by Django 5.2.3 on 2025-11-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_create',
            field=models.BooleanField(default=True, help_text='Allow user to create new items', verbose_name='Can Create'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_delete',
            field=models.BooleanField(default=False, help_text='Allow user to delete items', verbose_name='Can Delete'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_update',
            field=models.BooleanField(default=True, help_text='Allow user to update existing items', verbose_name='Can Update'),
        ),
    ]
