# Generated by Django 5.2.3 on 2025-11-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_can_create_user_can_delete_user_can_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'client'), ('boss', 'boss'), ('employe', 'employe'), ('guest', 'guest')], default='client', max_length=50, verbose_name='Role'),
        ),
    ]
