# Generated by Django 5.2.3 on 2025-10-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_province',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_house_number',
            field=models.CharField(default=1213, max_length=20, verbose_name='House Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_street',
            field=models.CharField(default=1, max_length=200, verbose_name='Delivery Street'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_location',
            field=models.CharField(choices=[('ardales', 'Ardales'), ('carratraca', 'Carratraca')], max_length=20, verbose_name='Delivery Location'),
        ),
    ]
