# Generated by Django 5.2.3 on 2025-11-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_delivery_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='customization',
            field=models.JSONField(blank=True, help_text='Product customization: selected ingredients, extras, and notes', null=True, verbose_name='Customization'),
        ),
    ]
