# Generated by Django 5.2.3 on 2025-11-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_customization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_location',
            field=models.CharField(help_text='Delivery location name (dynamically managed from company settings)', max_length=100, verbose_name='Delivery Location'),
        ),
    ]
