# Generated by Django 5.2.3 on 2025-11-02 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='be_extra',
            field=models.BooleanField(default=False, help_text='Indicates if this ingredient can be added as an extra to products', verbose_name='Can be Extra'),
        ),
    ]
