# Generated by Django 5.2.3 on 2025-11-12 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Internal title for admin reference', max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Text displayed at the bottom of the image', max_length=500, verbose_name='Description')),
                ('image', models.ImageField(help_text='Promotional banner image', upload_to='promotions/', verbose_name='Image')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this promotion is currently active', verbose_name='Active')),
                ('order', models.IntegerField(default=0, help_text='Order in which promotions are displayed (lower numbers first)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'db_table': 'promotions',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
