# Generated by Django 5.2.3 on 2025-11-12 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Text content displayed on the card', max_length=100, verbose_name='Text')),
                ('emoji', models.CharField(help_text='Emoji icon (e.g., 🍔, 🍕, 🌮)', max_length=10, verbose_name='Emoji')),
                ('background_color', models.CharField(default='#FF6B35', help_text='Hex color code for card background (e.g., #FF6B35)', max_length=7, verbose_name='Background Color')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this card is currently active', verbose_name='Active')),
                ('order', models.IntegerField(default=0, help_text='Order in carousel (lower numbers appear first)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Carousel Card',
                'verbose_name_plural': 'Carousel Cards',
                'db_table': 'carousel_cards',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
