# Generated by Django 5.2.3 on 2025-11-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='business_hours',
            field=models.TextField(blank=True, default='Lun-Dom: 08:00 - 23:00', verbose_name='Business Hours'),
        ),
        migrations.AddField(
            model_name='company',
            name='whatsapp_phone',
            field=models.CharField(default='+34623736566', max_length=20, verbose_name='WhatsApp Phone'),
        ),
    ]
