# Generated by Django 5.2.3 on 2025-11-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_business_hours_company_whatsapp_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='delivery_locations',
            field=models.JSONField(blank=True, default=list, help_text='List of delivery locations with id, name, value, and enabled fields', verbose_name='Delivery Locations'),
        ),
    ]
