# Generated by Django 5.2.3 on 2025-11-01 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='be_extra',
            field=models.BooleanField(default=False, help_text='Indicates if this product can be added as an extra to other products', verbose_name='Can be Extra'),
        ),
    ]
