# Generated by Django 5.2.3 on 2025-11-02 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_be_extra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='be_extra',
        ),
    ]
