# Generated by Django 5.2.3 on 2025-11-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productoption_product_options_productoptionchoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allows_extra_ingredients',
            field=models.BooleanField(default=True),
        ),
    ]
