# Generated by Django 5.2.3 on 2025-11-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_allows_extra_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allow_ingredient_swap',
            field=models.BooleanField(default=False, help_text='Allows swapping original ingredients for extras without additional charge (1 for 1)', verbose_name='Allow Ingredient Swap'),
        ),
    ]
